misc:
  exp_dir: tdmatch_ripoint_transformer_test
  gpu_mode: True
  verbose: True
  verbose_freq: 10
  mode: val
  debug: False
  output_metric_path: null

model:
  pretrain: 'pretrained/colabsfm.pth'
  transformer_architecture: ['self', 'cross', 'self', 'cross', 'self', 'cross']
  with_cross_pos_embed: True
  non_strict_loading: False
optim:
  optimizer: ADAM
  lr: 0.0001
  weight_decay: 0.000001
  momentum: 0.98
  scheduler: ExpLR
  scheduler_gamma: 0.95
  iter_size: 4

data:
  dataset: quad
  root: data/colabsfm/Quad/ArtsQuad_dataset/pointclouds/
  train_info: colabsfm/configs/quad/sift_infos.pkl
  val_info: colabsfm/configs/quad/sift_infos.pkl
  test_info: colabsfm/configs/quad/sift_infos.pkl
  augment_noise: 0.
  benchmark: colabsfm
  rotated: False
  colabsfm_mode: se3
  normal_orientation: viewpoint
  low_overlap: False
  use_color: False
  use_gray: False

coarse_matching:
  matching_radius: 0.1
  num_gt_coarse_corr: 128
  num_est_coarse_corr: 256
  coarse_overlap_threshold: 0.1

fine_matching:
  point_per_patch: 64
  fine_matching_topk: 3
  fine_matching_mutual: True
  fine_matching_confidence_threshold: 0.1
  fine_matching_use_dustbin: False
  fine_matching_use_global_score: False
  fine_matching_correspondence_threshold: 3

coarse_loss:
  coarse_loss_positive_margin: 0.1
  coarse_loss_negative_margin: 1.4
  coarse_loss_positive_optimal: 0.1
  coarse_loss_negative_optimal: 1.4
  coarse_loss_log_scale: 24
  coarse_loss_positive_overlap: 0.1
  coarse_loss_weight: 1.0

fine_loss:
  fine_loss_positive_radius: 0.1
  fine_loss_weight: 1.0
  fine_loss_use_mnn: False

occlusion_loss:
  occ_loss_weight: 0.0
  #occ_thres: 0.0

eval:
  eval_acceptance_overlap: 0.0
  eval_acceptance_radius: 0.1
  n_points_registration: 1000
  distance_threshold: 0.05
  ransac_n: 3
  rot_thresh: 5.
  trans_thresh: .05

train:
  max_epoch: 150
  batch_size: 1
  training_max_iter: 3500
  val_max_iter: 500
  scheduler_interval: 1
  snapshot_interval: 1
  num_workers: 4

glue:
  use_glue: false
  glue_refine: false

ppf:
  ppf_mode: "baseline"